### ISSUE TITLE
Clinical/Secondary Endpoints

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followd#1]
Weitere Klinische Endpunkte (Wir brauchen die in EINER Tabelle, auch wenn sie bei der K-M-Kurven oder AEs auch erwähnt sind:

- Cardiovascular death: 
AE.AEOUT=“Death“ AND MO.MOCS=“Cardiovascular” = `pp_endpoints$death_cause`

- In-hospital mortality: 
AE.AEOUT=“Death“ AND ((FU.FUDA {of visit=”discharge”} = Missing) OR (FU.FUDIL=”other”))
`pp_enpoints$died_before_discharge` = FUDA <= MODT

- All stroke (disabling and non disabling): 
AE.TYP = “Stroke: Disabling”  OR AE.TYP = “Stroke: Non-disabling”
`ae_custom$any_stroke`= aetype = (Stroke: Disabeling OR non-disabling OR TIA)

- Life-threatening bleeding:  (redundant, da bereits vorhanden)
AE.TYP = “Bleeding: Life-threatening” = `ae_custom$life_threatening_bleeding`

- Coronary artery obstruction requiring intervention: AE.TYP = “Coronary artery obstruction” AND AE.AEACT != NA
 `ae_custom$serious_coronary_obstruction` 

- Major vascular complication: AE.AETYP= “Major vascular complication” (redundant, da bereits vorhanden)

- Acute kidney injury – Stage 2 or 3:  
AE.AETYP = “Acute kidney injury: Stage 2” OR AE.AETYP = “Acute kidney injury: Stage 2”
`severe_kidney_injury`

- **Valve-related dysfunction requiring repeat procedure**: 
   - AE.AETYP = “Valve malpositioning: valve migration” OR
   - AE.AETYP = “Valve malpositioning: valve embolization” OR
   - AE.AETYP = “Valve malpositioning: ectopic valve deployment” OR
   - AE.AETYP = “Structural valve deterioration” OR
   - AE.AETYP = “Prosthetic valve endocarditis” OR
   - AE.AETYP = “Prosthetic valve thrombosis” AND
   - (AE.AEOUT != NA  AND FU.FUDA {Discharge} < AE.AEBD)
= `valve_dysfunction_before_discharge`

- New Pacemaker implantation:  
AE.AETYP = “Pacemaker implantation: pre-planned” OR AE.AETYP = “Pacemaker implantation: spontaneous”
= `pacemaker_implantation`

**Comment by rietzlers** [comment]
Ich würde alle secondary endpoints (die nicht schon anderswo als rohdaten vorliegen) in einem Datensatz, `secondary_endpoints` zusammenfassen.
Hierzu brauche ich noch einige Informationen:

- Haemodynamic parameters: Genaue Definition !? Zeitpunkt!? bzw. sind die schon vorhanden?
- NYHA classification: Genaue Definition!? bzw. sind die schon vorhanden

Was bedeutet "Early Safety" und was "Time related safety"

**Comment by rietzlers** [comment]
Die Variablen sind nun alle im Datensatz `ae_custom` vorhanden.

**Comment by wadepuhlm** [comment]
Closed, becaues all threads combined into one issue "clinical endpoints"
