### ISSUE TITLE
ae-custom ergänzen

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followd#16]
- Bitte noch labels bei event_time, primary_caues einfügen

- variabel event_anticpated fehlt

- für das longlisting sind die ursprünglichen relationen notwendig

- mit serious ==1 bzw serious ==0 kann ich nicht auf serious und not serious AE filtern (obwohl der Code YESNO das fordern würde???

**Comment by rietzlers** [comment]
fehlende labels und variablen habe ich jetzt ergänzt. 
Filter funktioniert bei mir. Allerding muß man im klartext filtern, d.h. z.B.  
serious == "YES"
