### ISSUE TITLE
pdf Report Tabellenbreite

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followd#19]
Die Tabellen gehen teilweise über die Seite hinaus. Beispiel Tab. 3.15 Distance, Diameter,...

**Comment by wadepuhlm** [comment]
Habe gerade ausprobiert: wenn man das 'full_width = FALSE' rausnimmt, dann passt es wieder. Ich gehe jetzt das Programm durch und adjustiere diese Option!

**Comment by rietzlers** [comment]
gut. dann schließe ich dieses issue
